### PR TITLE
Bump syntex_syntax version

### PR DESCRIPTION
**Pull request by mcasper**
Fixes the cascade of dependency breakages introduced in
https://github.com/rust-lang/rust/pull/29850

### CODE REVIEW

**Comment by chills42** [comment]
Cool, so this fixes a breaking change in syntax that affected our dependency?

**Comment by mcasper** [comment]
Yep! `dotenv_codegen` doesn't currently build on the latest nightly, this fixes that.

**Comment by mfpiccolo** [comment]
@chills42 @slapresta This change has been confirmed and merge into diesel.  Green light to merge this?

**Comment by chills42** [comment]
Looks great!

**Pull request merged**
