### PR TITLE
Allow colon : to be used as key,val separator

### PR DESCRIPTION
**Pull request by elifoster**
The Ruby gem, which is quoted in the README, permits this, and as such, I expected this crate to allow it as well. Turns out, it doesn't :cry:

### CODE REVIEW

**Comment by slapresta** [comment]
Thoughts on this? @sgrif @alicemaz

**Comment by alicemaz** [comment]
My kneejerk reaction is "what no that breaks sourcing the file in the shell." But I suppose .env files aren't typically shared so it's unlikely to impact anyone that didn't do it that way themself. No strong opinion either way.

**Comment by sgrif** [comment]
The ruby gem allows this and I've never seen a good reason for it. I don't think it's worth supporting unless there's a legitimate use case

**Comment by slapresta** [comment]
I'm closing this one for now. Thanks for your contribution, @elifoster, but I'm not sure we need this at the moment. If you'd like to discuss this further, please open an issue about it.

**Pull request closed without merging**
