### PR TITLE
Bump syntex version.

### PR DESCRIPTION
**Pull request by SergioBenitez**
Everything seems to work okay with the latest syntex.

### CODE REVIEW

**Comment by slapresta** [comment]
Thank you @SergioBenitez!

@sgrif, could you quickly confirm that this is the right approach? I know that we're doing versioning for syntex bumps differently now. This is how it's supposed to be done, isn't it?

**Comment by sgrif** [comment]
Yes this is correct.

**Comment by sgrif** [comment]
I've been bumping the patch version if we only increase the max allowed version, and bumping the minor version when the min allowed version changes

**Comment by slapresta** [comment]
Thanks, @sgrif! Merging :100:

**Pull request merged**
